[package]
name = "usermanapi"
version = "0.1.0"
authors = ["freied"]

[dependencies]
rocket = "0.3.14"
rocket_codegen = "0.3.14"
rocket_contrib = "0.3.14"
rocket_cors = "0.2"

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
